#!/bin/bash
source $HOME/foam/foam-extend-4.0/etc/bashrc

echo blockMesh meshing...
blockMesh -region fluid > blockMeshFluid.log
blockMesh -region solid > blockMeshSolid.log

echo Preparing 0 folder...
cp -r 0/fluid/U.org 0/U
cp -r 0/fluid/alpha1.org 0/alpha1

echo Setting the fields...
mv constant/fluid/waveDict constant/waveDict
mv constant/fluid/polyMesh constant/polyMesh
sed -i '/newMovingWallVelocity/s/newMovingWallVelocity/movingWallVelocity/g' 0/U

#setOla > setOla.log
setFields > setFields.log
sed -i '/movingWallVelocity/s/movingWallVelocity/newMovingWallVelocity/g' 0/U
mv 0/U 0/fluid/U
mv 0/alpha1 0/fluid/alpha1
mv constant/waveDict constant/fluid/waveDict
mv constant/polyMesh constant/fluid/polyMesh

# Run parallel
echo Running parallel...
decomposePar -region fluid > decomposeParFluid.log
decomposePar -region solid > decomposeParSolid.log
mpirun -np 3 solids4Foam -parallel > log.solids4Foam

#echo Running serial...
#runApplication solids4Foam

echo Simulation complete.
